// ------------------------------------------------------------------------------------------
const { faker } = require('@faker-js/faker');
const mysql = require('mysql2');
// -------------------------------------------------------------------------------------------
// using fekar  
// let createRandomUser=()=> {  
              //     return {
              //       userId: faker.string.uuid(),
              //       username: faker.internet.userName(),
              //       email: faker.internet.email(),
              //       password: faker.internet.password()
              //      avatar: faker.image.avatar(),
              //       birthdate: faker.date.birthdate(),
              //      registeredAt: faker.date.past(),
              //     };
              //   }
              //   console.log(createRandomUser());
//--------------------------------------------------------------------------------------------

// Create the connection to database
const connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    database: 'abcd',
    password:'1234',
    multipleStatements: true // *****
  });
//  ----------------------------------------------------------------------------------------
// runing first query
            // try{
            //   connection.query("show tables",(err,result)=>{  // running a query on data base , printing result using try and catch
            //                                                   // using this we can only execute single query 
            //                                                   // to execute mutiple query we have two options
            //                                                     // we can use one query inside another query or do *****
            //   if(err) throw err;
            //   console.log(result);
            // });
            // }catch(err){
            //   console.log(err);
            // }
  // ----------------------------------------------------------------------------------------
  // using multiple query
          // connection.query("show tables;select id from user",(err,result)=>{ 
          //   console.log(result);
          // });
// ---------------------------------------------------------------------------------------------
// using variable for query
          // let q="insert into user (id,username,email,password) values(?,?,?,?)"; // ? is used to provide dynamic values
            // let user=["123","name1","email1","pass1"];
            // try{
            //   connection.query(q,user,(err,result)=>{
            //     if(err) throw err;
            //     console.log(result);
            //   });
            //   }catch(err){
            //     console.log(err);
            //   }

// -------------------------------------------------------------------------------------------------
// insert multiplle user onces using variable
          let q="insert into user (id,username,email,password) values ?"; // as multiple data  so  sigle ?
          // users=[
          //   ["124","name2","email2","pass2"],
          //   ["125","name3","email3","pass3"],
          // ];
          // try{
          //   connection.query(q,[users],(err,result)=>{  // notice this line [users] is witten as users is a array
          //     if(err) throw err;
          //     console.log(result);
          //   });
          //   }catch(err){
          //     console.log(err);
          //   }
// -------------------------------------------------------------------------------------------------
//insert multiplle user onces using variable and taking data from faker
              
          let user=()=>{
            return[ // returning the values generated by faker
              faker.string.uuid(),
              faker.internet.userName(),
              faker.internet.email(),
              faker.internet.password()
            ];
          };
          //------
          let data=[];
          for(let i=0;i<100;i++)
          {
            data.push(user());
          }
          //------
          try{
              connection.query(q,[data],(err,result)=>{  // notice this line [users] is witten as users is a array
                if(err) throw err;
                console.log(result);
              });
              }catch(err){
                console.log(err);
              }

          

// ---------------------------------------------------------------------------------------------------
connection.end();
